[request_definition]
r = sub, svc, tool

[policy_definition]
p = sub, svc, tool, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && (p.svc == "*" || r.svc == p.svc) && (p.tool == "*" || r.tool == p.tool)
